version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_PYTHON_API_URL: http://localhost:5371
      PYTHON_API_URL: http://backend:5371
    depends_on:
      - backend
    volumes:
      - ./.env.local:/app/.env.local:ro
    networks:
      - llm_benchmark_net

  backend:
    build:
      context: ./python-benchmark-service
      dockerfile: Dockerfile
    ports:
      - "5371:5371"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    networks:
      - llm_benchmark_net

networks:
  llm_benchmark_net:
    driver: bridge
