[project]
name = "python-benchmark-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "litellm>=1.68.1",
    "python-dotenv>=1.1.0",
    "werkzeug>=3.1.3",
]
